#!/bin/bash

# SearchBook PostgreSQL Setup Script
# This script helps set up the .env file for app2

set -e

echo "╔═══════════════════════════════════════════════════════════════════════╗"
echo "║           SearchBook PostgreSQL - Environment Setup                  ║"
echo "╚═══════════════════════════════════════════════════════════════════════╝"
echo ""

APP2_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$APP2_DIR/.env"
ENV_EXAMPLE="$APP2_DIR/.env.example"

# Check if .env already exists
if [ -f "$ENV_FILE" ]; then
    echo "⚠️  .env file already exists at $ENV_FILE"
    read -p "Do you want to overwrite it? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "✓ Using existing .env file"
        exit 0
    fi
fi

# Create .env from template or scratch
echo "📝 Creating .env configuration..."

# Default values
DEFAULT_POSTGRES_USER="searchbook"
DEFAULT_POSTGRES_PASSWORD="searchbook_password"
DEFAULT_POSTGRES_DB="searchbook"
DEFAULT_API_URL="http://localhost:8000/api"

# Prompt for values (with defaults)
read -p "PostgreSQL username (default: $DEFAULT_POSTGRES_USER): " POSTGRES_USER
POSTGRES_USER="${POSTGRES_USER:-$DEFAULT_POSTGRES_USER}"

read -sp "PostgreSQL password (default: $DEFAULT_POSTGRES_PASSWORD): " POSTGRES_PASSWORD
echo
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$DEFAULT_POSTGRES_PASSWORD}"

read -p "PostgreSQL database name (default: $DEFAULT_POSTGRES_DB): " POSTGRES_DB
POSTGRES_DB="${POSTGRES_DB:-$DEFAULT_POSTGRES_DB}"

read -p "Frontend API URL (default: $DEFAULT_API_URL): " API_URL
API_URL="${API_URL:-$DEFAULT_API_URL}"

# Create .env file
cat > "$ENV_FILE" << EOF
# SearchBook PostgreSQL Configuration
# Generated by setup.sh on $(date)

# PostgreSQL Configuration
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=$POSTGRES_DB

# Backend Configuration (must match PostgreSQL settings)
SEARCHBOOK_DB_HOST=postgres
SEARCHBOOK_DB_PORT=5432
SEARCHBOOK_DB_NAME=$POSTGRES_DB
SEARCHBOOK_DB_USER=$POSTGRES_USER
SEARCHBOOK_DB_PASSWORD=$POSTGRES_PASSWORD

# Application Settings
SEARCHBOOK_PROJECT_NAME=SearchBook
SEARCHBOOK_API_PREFIX=/api
SEARCHBOOK_MIN_WORD_COUNT=10000
SEARCHBOOK_BM25_RESULTS_LIMIT=50
SEARCHBOOK_SUGGESTIONS_LIMIT=5

# Frontend API URL
VITE_API_BASE_URL=$API_URL
EOF

echo ""
echo "✅ .env file created successfully at $ENV_FILE"
echo ""
echo "📋 Configuration Summary:"
echo "   PostgreSQL User:     $POSTGRES_USER"
echo "   PostgreSQL Password: $(echo $POSTGRES_PASSWORD | sed 's/./*/g')"
echo "   Database Name:       $POSTGRES_DB"
echo "   Frontend API URL:    $API_URL"
echo ""
echo "🔒 Security Note:"
echo "   - The .env file is listed in .gitignore and will NOT be committed"
echo "   - Never share your .env file or push it to version control"
echo "   - Use strong passwords in production environments"
echo ""
echo "🚀 Next steps:"
echo "   1. Review the .env file: cat $ENV_FILE"
echo "   2. Start services: docker compose up --build"
echo "   3. Load books: python ingestion/load_books.py --corpus-path ../datasets/sample_books"
echo ""
